### ISSUE TITLE
shared cloudant broken - dbname now defaults to "nodered", not sanitized appname

### ISSUE THREAD

**Issue by ibmrcruicks** [IBM/node-red-app#42] opened 2021-01-29 10:51 UTC
Unwelcome change of behaviour !

when creating a new app instance, but sharing existing Cloudant instance, expected behaviour is an app-specific db will be created to hold app flows.
recent update (Sept 2020) defaults this to NodeRED if using the [Starter Kit dialog in IBM Cloud](https://cloud.ibm.com/developer/appservice/create-app?starterKit=59c9d5bd-4d31-3611-897a-f94eea80dc9f&defaultLanguage=undefined)  -- app deploys OK, but will point to a previous nodered db instead of creating a new one.

No mention of option to override with NODE_RED_STORAGE_DB_NAME  and nowhere to set that in the Starter kit dialog.

Now effective failure to benefit from sharing cloudant instance

**Comment by knolleary** [comment] 2021-01-29 11:04
This change in behaviour was introduced by #21 

https://github.com/IBM/node-red-app/pull/21/files#diff-b8ffd4404cf2babfda8ca064a27e0b88469d77b60dec6fbbbec13946bcd84c16R101

The code is meant to be using the app's name to key into the database so the service instance can be easily shared by multiple applications.

For some reason that was changed in the above PR which doesn't mention anything about changing this particular behaviour.

**Comment by youming-lin** [comment] 2021-01-29 16:52
The change was made to use `ibm-cloud-env` instead of `cfenv` in order to standardize this app to run on Cloud Foundry and Kubernetes (and now Code Engine as well). We can do some investigation to see if these new deployment environments have app name exposed to the running application, but we are currently shorthanded so I don't know when will we get around to this.

**Comment by ibmrcruicks** [comment] 2021-01-29 18:08
The chnage made breaks a very usual capability in the most common deployment environment for Node-RED (CloudFoundry), and it seems little investigation was undertaken to see how to preserve that capability in other environments.

**Comment by ibmrcruicks** [comment] 2021-01-29 18:27
sadly Cloud Foundry runtime instances also have a HOSTNAME variable, which does not include the app name, 
but VCAP_APPLICATION["application_name"] value could have precedence if it exists

**Comment by youming-lin** [comment] 2021-01-29 19:50
No schedule right now. I've opened issue internally; we'll talk about it within our team and determine priority.

`VCAP_APPLICATION["application_name"]` is probably what `cfenv` looked at, but we'll need to find equivalents for Kube and Code Engine.

**Comment by knolleary** [comment] 2021-01-29 20:02
A quick pragmatic solution would be to check if `process.env.VCAP_APPLICATION` exists, and if it does, parse it and pull out `application_name`. That would at least get it working again in the CF env whilst you figure out the appropriate alternative for the other environments.

The majority of uses still deploy to CF because that's what all of our docs and tutorials point to.

**Comment by ibmrcruicks** [comment] 2021-03-01 10:21
let's not close thisuntil there is an update from @youming-lin with anticipated date for correcting behaviour

**Comment by knolleary** [comment] 2021-03-01 11:05
@ibmrcruicks absolutely - have removed the stale label

**Comment by ibmrcruicks** [comment] 2021-03-31 13:49
another month gone by -- what is the current plan? we have students trying to go through workshops, building node-red based AI applications, then trying to create node-red IOT apps, and discovering their previous app flows in the new app.

**Comment by youming-lin** [comment] 2021-03-31 19:36
I'll work on a fix for CF. I don't have a good solution to discover app name in Kube, but since most users use CF I'll fix this for that deployment target for now. Between lack of resources (the flesh and bone kind) and other 1Q commitments, this was not high on our priority list.

And as always, since this is an open source project, we welcome PRs by other developers.

Also, I'll have to be honest: sharing a single Cloudant instance with multiple instances of this starter kit (and expecting different DBs for each instance) is not a scenario we expected. Are multiple users sharing the same free IBM Cloud account or something?

**Comment by knolleary** [comment] 2021-03-31 19:55
Thanks for looking at this.

> Are multiple users sharing the same free IBM Cloud account or something?

No, but one user may want to deploy multiple copies of the starter kit.

Back in the original days of the boilerplate, we were asked by the cloudant team to pool instances like this as we were the number 1 consumer of Cloudant instances in their free tier.

**Comment by youming-lin** [comment] 2021-04-08 16:06
Implemented in #52

**Comment by youming-lin** [comment] 2021-04-09 14:45
@ibmrcruicks 
The change should be live on production now. Can you redeploy a Node-RED starterkit to Cloud Foundry again and see if it's working? Fix has been implemented for Cloud Foundry and Code Engine but not IKS yet.

**Comment by ibmrcruicks** [comment] 2021-04-13 14:21
definitely not  working -- the pipelines deployed are tekton pipelines for ci and pr -- not the expected build/deploy stages for cloud foundry
<img width="404" alt="Screenshot 2021-04-13 at 15 17 11" src="https://user-images.githubusercontent.com/25483279/114568282-e73e8500-9c6b-11eb-9d30-669a2712fef3.png">
<img width="393" alt="Screenshot 2021-04-13 at 15 17 18" src="https://user-images.githubusercontent.com/25483279/114568285-e7d71b80-9c6b-11eb-8d56-b10e05bb38f2.png">
<img width="796" alt="Screenshot 2021-04-13 at 15 18 15" src="https://user-images.githubusercontent.com/25483279/114568286-e86fb200-9c6b-11eb-8efa-a85b06d502b6.png">
<img width="941" alt="Screenshot 2021-04-13 at 15 18 29" src="https://user-images.githubusercontent.com/25483279/114568289-e9084880-9c6b-11eb-9824-bfd2161ef724.png">

**Comment by youming-lin** [comment] 2021-04-13 14:51
We are aware of the new GitHub requirement imposed by the Tekton pipeline and are investigating a fix.

As for the memory issue, I've not been able to reproduce. I just tested deploying Node-RED skit to CF and I see a `manifest.yml` file in the code repo with `256MB` memory.

>the toolchain seems to deploying all the deployment options regardless of the target selection (Cloud Foundry in our cases)

Not sure what you mean by that, but we do currently still include Dockerfile even for CF deployment due to legacy behavior that we haven't changed yet.

**Comment by ibmrcruicks** [comment] 2021-04-13 16:04
to reproduce -
get a nice fresh  IBM Cloud LITE account (in production) 
select node-red app from catalog
accept appropriate defaults, making sure all the region settings match your account capabilities
process the `Deploy your app`
watch the `Deployment Automation` section lose the status updates
check the status of the resulting toolchain

**Comment by ibmrcruicks** [comment] 2021-04-13 16:06
regarding the "all the deployments" comment - what other explanation is there for 3 github clones? (well 2 really, because 1 fails for unreported reasons)

**Comment by ibmrcruicks** [comment] 2021-04-13 16:07
#58

**Comment by ibmrcruicks** [comment] 2021-04-13 16:08
re Tekton - are you  indicating that the `Classic` pipeline model has  been replaced  by a Tekton-based approach instead?

**Comment by youming-lin** [comment] 2021-04-13 16:11
> re Tekton - are you indicating that the Classic pipeline model has been replaced by a Tekton-based approach instead?
Yes. Migrating to Tekton was on our Q1 roadmap, which we completed for CF and Helm toolchains at end of March. This is why you see 3 repos now (1 GitLab for code, 1 GitLab for pipeline, and one GitHub integration for the public Tekton tasks hosted in https://github.com/open-toolchain/tekton-catalog).

**Comment by ibmrcruicks** [comment] 2021-04-13 16:57
thanks - so which git clone fails in the above screenshot? and why?

**Comment by youming-lin** [comment] 2021-04-13 17:10
The failure in the screenshot is from the GitHub integration. Unfortunately, Tekton pipelines added a new requirement on GitHub integration. What this means is that the user must grant IBM Cloud DevOps Toolchains access to their public GitHub account. It is a limitation that the DevOps team is looking to eliminate; I believe it was originally added due to GitHub API rate limits. With account permission, DevOps can then clone the tekton-catalog repo (which contains all the Tekton tasks to scan/build/deploy applications) as the user and avoid the rate limiting for anonymous usage.

**Comment by ibmrcruicks** [comment] 2021-04-13 17:28
i don't see any instructions in this repo regarding the user having to doing anything with any github accounts -- this process has worked perfectly well, cloning the repo into the users' gitlab accounts without any prior setup, and as such, users  have a simple expectation that selecting the starter kit from the IBM Cloud catalog, it will work.
Is that no longer true?, and if so, what needs to change (very quickly) to get the off-the-shelf experience working again?

**Comment by youming-lin** [comment] 2021-04-13 17:58
Right now we have a doc on how to manually fix the GitHub integration issue: https://cloud.ibm.com/docs/apps?topic=apps-managingapps#setup-failed-toolchain-ts

Long term fix would be for the DevOps team to remove this requirement. For short term fix, I'm still discussing with my team on how to go about addressing this issue temporarily (since we are expecting DevOps to implement the permanent fix eventually).

**Comment by jmeis** [comment] 2021-04-21 13:06
I believe the original issue was fixed here -- going to close the issue but feel free to re-open if the shared db name is not working as expected.

**Closed by jmeis** 2021-04-21 13:06 UTC
Labels: keep-open
